default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )

    cert(api_key: api_key)

    sigh(
      app_identifier: "com.watahiki.BiteLog",
      api_key: api_key,
      force: true
    )

    gym(
      scheme: "BiteLog",
      export_method: "app-store-connect",
      configuration: "Release",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
