name = "bitelog-workers"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bitelog"
database_id = "cf39b710-956c-4f27-ae1a-6dbf7a6a0fef"

[vars]
# 本番では wrangler secret put WORKER_JWT_SECRET で上書きすること
WORKER_JWT_SECRET = "dev-and-test-secret"

[dev]
port = 8787
